<a href="https://colab.research.google.com/github/Hieudo02/AI-Exercise/blob/main/buoi5_20_03_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.linear_model import Perceptron

#hang: so luong mau
#cot: so dac tinh (bao nhieu bien)
x = [[0, 0], [0,1], [1,0], [1,1]]
y = [0, 1, 1, 1]

#tao mo hinh
model = Perceptron()
#train
model.fit(x, y)
#evaluate (danh gia do chinh xac)
model.score(x, y)

In [ ]:
#thu tien doan
x1 = [[0.5, -1], [0.5, 0.5], [-10, 1], [0.29, 0.29]]
y1 = model.predict(x1)
print(y1)
model.score(x1, y1)

In [ ]:
#example
from sklearn.linear_model import Perceptron

x1 = [[-0.5, -0.5], [-0.5, -0.5], [0.3, -0.5], [-0.1, 1]]
x2 = [1, 1, 0, 0]

#create model
model = Perceptron()
#training
model.fit(x1, x2)
#precision evaluating
model.score(x1, x2)

#predict
a = [[-0.9, -0.9], [-10, -10], [-1, -1], [-5, -5]]
b = model.predict(a)
print(b)
model.score(a, b)

In [52]:
#iris
from sklearn import datasets                         #thu muc chua du lieu : init (0-9), ...
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split #chia du lieu lam 2 phan: train va test
from sklearn.metrics import accuracy_score           #do luong (measure: do chinh xac, mat mat (lost), ...)
from sklearn.preprocessing import StandardScaler     #khi data khong deu nhau => chuan hoa du lieu (scaler) (DU LIEU NAY KHONG PHAI THUC TE)

#load data
iris = datasets.load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [72]:
#trong iris co du lieu "data" va "target"
X = iris.data
Y = iris.target
print(X[:5])
print(Y[:5])

#chia train va test
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3) #testsize = 0.3 => trainsize = 0.7
#scale du lieu
sc = StandardScaler()
#training
sc.fit(X_train)

X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [73]:
model = Perceptron(max_iter = 40, eta0 = 0.1, random_state = 0)    #so lan hoc: 40 lan
                                                                  #toc do hoc: 0.1 (cang lon sai so cang nhieu) (la so duong)
                                                                  #trang thai lay gia tri: 0
model.fit(X_train_std, Y_train)
Y_pred = model.predict(X_test_std)
print(Y_pred)
print(Y_test)
print("Do chinh xac cua mo hinh: ", accuracy_score(Y_test, Y_pred))

[1 0 2 1 2 2 0 2 0 2 2 1 1 2 0 0 0 2 0 0 0 0 2 2 1 2 2 2 1 1 2 0 1 2 1 2 2
 2 2 0 1 0 0 0 0]
[1 0 2 1 2 2 0 2 0 2 2 1 2 2 0 0 0 1 0 0 0 0 2 2 1 2 1 2 1 1 2 0 1 2 1 2 2
 1 2 0 2 0 0 0 0]
Do chinh xac cua mo hinh:  0.8888888888888888


In [99]:
import pandas as pd
import numpy as np
url = 'crabs.csv'
data = pd.read_csv(url)

data1 = data[(data['speies'] =='B')] 

#Xoa cot 'sex' cu~ di va thay the bang cot 'sex' co chi so M, F dc thay the bang 1, 0
y = data['sex']
data = data.drop(data.columns[[0]], axis = 1)
data = data.replace("M",1)
data = data.replace("F",0)
data.head()

sex  index  fontallip  rearwidth  length  width  depth
0    1      1        8.1        6.7    16.1   19.0    7.0
1    1      2        8.8        7.7    18.1   20.8    7.4
2    1      3        9.2        7.8    19.0   22.4    7.7
3    1      4        9.6        7.9    20.1   23.1    8.2
4    1      5        9.8        8.0    20.3   23.0    8.2

In [100]:
X = data[['fontallip', 'rearwidth', 'length', 'width', 'depth']].to_numpy()
Y = data['sex'].to_numpy()

#chia train va test
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3) #testsize = 0.3 => trainsize = 0.7
#scale du lieu
sc = StandardScaler()
#training
sc.fit(X_train)

X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

model = Perceptron(max_iter = 40, eta0 = 0.1, random_state = 0)    #so lan hoc: 40 lan
                                                                  #toc do hoc: 0.1 (cang lon sai so cang nhieu) (la so duong)
                                                                  #trang thai lay gia tri: 0
model.fit(X_train_std, Y_train)
Y_pred = model.predict(X_test_std)
print(Y_pred)
print(Y_test)
print("Do chinh xac cua mo hinh: ", accuracy_score(Y_test, Y_pred))

[1 0 1 0 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 1 0 1 0 1 1 1 0 0
 0 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0]
[0 0 0 0 1 1 0 1 1 1 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 1 0 1 0 1 1 1 0 0
 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 1 0]
Do chinh xac cua mo hinh:  0.85
